// Code generated by provider-maker. DO NOT EDIT.

package constructor

import (
	"github.com/google/wire"
	"github.com/yukiouma/provider-maker/examples/demo/adapter/datasource"
	"github.com/yukiouma/provider-maker/examples/demo/usecase"
)

var Providers = wire.NewSet(
	datasource.NewRepo,
	usecase.NewUsecase,
)
